#! /bin/bash
if [ "$1" == "" ] ; then
echo "you need a word you want to check"
exit 0;
fi


for i in $@; do
echo -e "\n~~~@~~~"
wn $i -synsn | sed '1,6d' |sed 's/Sense [[:digit:]]//g' | sed 's/[[:space:]]*=> //' | sed '/^$/d' | sed 's/ //g' | grep -iv $i | tr '\n' ' ';
echo -e "\n~~~@~~~"
wn $i -synsv | sed '1,6d' |sed 's/Sense [[:digit:]]//g' | sed 's/[[:space:]]*=> //' | sed '/^$/d' | sed 's/ //g' | grep -iv $i | tr '\n' ' ';
echo -e "\n~~~@~~~"
wn $i -hypen | sed '1,6d' |sed 's/Sense [[:digit:]]//g' | sed 's/[[:space:]]*=> //' | sed '/^$/d' | sed 's/ //g' | grep -iv $i | tr '\n' ' ';
echo -e "\n~~~@~~~"
wn $i -hypon | sed '1,6d' |sed 's/Sense [[:digit:]]//g' | sed 's/[[:space:]]*=> //' | sed '/^$/d' | sed 's/ //g' | grep -iv $i | tr '\n' ' ';
echo -e "\n~~~@~~~"
done;
